##### Admin CMS APIs


##################### User Router ################
### root api
GET http://localhost:8000/

### Create new user
POST http://localhost:8000/api/v1/user/
Content-Type: application/json

{
    "fname": "Bijay",
    "lname": "Nagarkoti",
    "email":"a@gmail.com",
    "dob": "1997-12-14",
    "password":"12345678",
    "phone":"0410684026",
    "address":"8/29-30 Mary Street, Lidcombe",
    "gender":"Male"
}

### Verify admin email
PATCH http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "pin":"312710",
    "email":"bijay02@gmail.com"
}
### User Login
POST  http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email":"a@gmail.com",
    "password":"12345678"
}


######################  Catalog router   ##################

### Get all categories or single category
GET http://localhost:8000/api/v1/category/

### Create new category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "name":"Home and Garden",
    "parentCat":null
}

###Update category
PATCH  http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "_id":"61a068bbe79cb9247602acd6",
    "name":"Home",
    "parentCat":"61a06420420955ad81ef1a57"
}

### Delete category
DELETE  http://localhost:8000/api/v1/category/61a0ddd54b2e94055b113


###############   Token Router

### get new access token

GET http://localhost:8000/api/v1/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNjM5MTA1ODgxLCJleHAiOjE2NDE2OTc4ODF9.qSixbSl5aT3JjPe07vkVn1TgkCigtvEyXUcAwv5KdKQ