##### Admin CMS APIs


##################### User Router ################
### root api
GET http://localhost:8000/

### Create new user
POST http://localhost:8000/api/v1/user/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNjQwNDc0MjIwLCJleHAiOjE2NDA0NzUxMjB9.eRsJzl46QuMbIpZATmiQK79iD5JsMoKBpaoJJeTeCCU

{
    "fname": "Bijay",
    "lname": "Nagarkoti",
    "email":"a@gmail.com",
    "dob": "1997-12-14",
    "password":"12345678",
    "phone":"0410684026",
    "address":"8/29-30 Mary Street, Lidcombe",
    "gender":"Male"
}

### Verify admin email
PATCH http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "pin":"312710",
    "email":"bijay02@gmail.com"
}
### User Login
POST  http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email":"a@gmail.com",
    "password":"12345678"
}



### User Logout 
POST  http://localhost:8000/api/v1/user/logout
Content-Type: application/json

{
  "accessJWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNjQwNTExMDk3LCJleHAiOjE2NDA1MTE5OTd9.crWyHVtANMFazj5LT4ZpSiHAPQaSLgcHpPTLlsWjM28",
    "refreshJWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNjQwNTExMDk3LCJleHAiOjE2NDMxMDMwOTd9.Y3jOS1tCRSZw8yes--xwg8yHseNcaIDPSXYciNpVB0E"
}
### Admin Password Update
POST  http://localhost:8000/api/v1/user/password-update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNjQxNzA4ODUxLCJleHAiOjE2NDE3MDk3NTF9.7y4NaLp9QrPnZqbWOjAXtmleVsYM5MMt8uZsZLkZO-I

{
  "currentPassword":"Aa1*12345dfaff",
  "password":"1aA!1111"
}
### Reset new password 
POST  http://localhost:8000/api/v1/user/reset-password
Content-Type: application/json

{
    "otp":122222,
  "newPassword":"1aA!1111"
}


######################  Category router   ##################

### Get all categories or single category
GET http://localhost:8000/api/v1/category/

### Create new category
POST http://localhost:8000/api/v1/category
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNjQwNDc0MjIwLCJleHAiOjE2NDA0NzUxMjB9.eRsJzl46QuMbIpZATmiQK79iD5JsMoKBpaoJJeTeCCU

{
    "name":"Kitchen",
    "parentCat":null
}

###Update category
PATCH  http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "_id":"61a068bbe79cb9247602acd6",
    "name":"Home",
    "parentCat":"61a06420420955ad81ef1a57"
}

### Delete category
DELETE  http://localhost:8000/api/v1/category/61a0ddd54b2e94055b113


##################   Token Router  ##################

### get new access token

GET http://localhost:8000/api/v1/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNjQwNTIwNjYwLCJleHAiOjE2NDMxMTI2NjB9.bRXBvf2rrBuo9yGp8010hiinlB8KFkmNXmgE82nP_-Q



### User forgot password OTP request
POST  http://localhost:8000/api/v1/token/request-otp
Content-Type: application/json

{
    "email":"a@gmail.com"
}
