##### Admin CMS APIs

### root api
GET http://localhost:8000/

### Create new user
POST http://localhost:8000/api/v1/user/
Content-Type: application/json

{
    "fname": "Bijay",
    "lname": "Nagarkoti",
    "email":"bijay02@gmail.com",
    "dob": "1997-12-14",
    "password":"12345adafsdf",
    "phone":"0410684026",
    "address":"8/29-30 Mary Street, Lidcombe",
    "gender":"Male"
}

### Verify admin email
PATCH http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "pin":"312710",
    "email":"bijay02@gmail.com"
}